### ISSUE TITLE
expand templates to allow specification of timezone

### ISSUE THREAD

**Issue by b2cc** [gerald1248/openshift-backup#11]
Please excuse my nagging... I noticed that time in the suffix of the backupfiles is off since the container runs in UTC per default. Although im aware this is a rather minor nuisance it can easily be fixed by injecting the "TZ" environment variable:

```
spec:
  template:
    spec:
      containers:
      - env:
        - name: TZ
          value: "Europe/Berlin"
```

I guess this could be added to the "exports" file with a default of "UTC" if not specified otherwise.
